package gui;

import bl.TableRenderer;
import bl.WetterBl;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lb
 */
public class WeatherGUI extends javax.swing.JFrame {

    private bl.WetterBl bl = new WetterBl();
    
    public WeatherGUI() {
        initComponents();
        tabWheater.setModel(bl);
        tabWheater.setDefaultRenderer(Object.class, new TableRenderer());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabWheater = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAdd = new javax.swing.JMenuItem();
        miRemove = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miSetTemp = new javax.swing.JMenuItem();
        miSetHum = new javax.swing.JMenuItem();
        muSLvl = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabWheater.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(tabWheater);

        jMenu1.setText("Stations");

        miAdd.setText("Add Weather Station");
        miAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miAddActionPerformed(evt);
            }
        });
        jMenu1.add(miAdd);

        miRemove.setText("Remove Weather Station");
        miRemove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miRemoveActionPerformed(evt);
            }
        });
        jMenu1.add(miRemove);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Values");

        miSetTemp.setText("Set Temperature");
        miSetTemp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miSetTempActionPerformed(evt);
            }
        });
        jMenu2.add(miSetTemp);

        miSetHum.setText("Set Humidity");
        miSetHum.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miSetHumActionPerformed(evt);
            }
        });
        jMenu2.add(miSetHum);

        jMenuBar1.add(jMenu2);

        muSLvl.setText("SealLvl");

        jMenuItem1.setText("hide");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        muSLvl.add(jMenuItem1);

        jMenuItem2.setText("show");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        muSLvl.add(jMenuItem2);

        jMenuBar1.add(muSLvl);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddActionPerformed
        WeatherDlg2 dlg = new WeatherDlg2(this, true);
        dlg.setVisible(true);
        
        if(dlg.isOkay())
        {
            bl.add(dlg.getWs());
        }
    }//GEN-LAST:event_miAddActionPerformed

    private void miRemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miRemoveActionPerformed
    {//GEN-HEADEREND:event_miRemoveActionPerformed
        int idx[] = tabWheater.getSelectedRows();
        
        for(int i = idx.length-1; i >= 0; i--)
            bl.del(idx[i]);
    }//GEN-LAST:event_miRemoveActionPerformed

    private void miSetTempActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miSetTempActionPerformed
    {//GEN-HEADEREND:event_miSetTempActionPerformed
        bl.WetterStation ws = (bl.WetterStation)bl.getValueAt(tabWheater.getSelectedRow(), 0);
        
        try
        {
            ws.setTemp(Integer.parseInt(JOptionPane.showInputDialog("Change Temp")));
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_miSetTempActionPerformed

    private void miSetHumActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miSetHumActionPerformed
    {//GEN-HEADEREND:event_miSetHumActionPerformed
         bl.WetterStation ws = (bl.WetterStation)bl.getValueAt(tabWheater.getSelectedRow(), 0);
        
        try
        {
            ws.setHum(Integer.parseInt(JOptionPane.showInputDialog("Change Hum")));
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_miSetHumActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
       bl.setHide(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
       
        bl.setHide(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JMenuItem miRemove;
    private javax.swing.JMenuItem miSetHum;
    private javax.swing.JMenuItem miSetTemp;
    private javax.swing.JMenu muSLvl;
    private javax.swing.JTable tabWheater;
    // End of variables declaration//GEN-END:variables

}
